main:
  tracking_uri: "http://127.0.0.1:5000"
  experiment_name: "development"
  steps: "all"
download:
  uri: "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
  file_name: "iris.data"
  s3_path: "raw_data"
clean:
  raw_data: "../get_data/data/iris.data"
  file_name: "iris.csv"
  col_names: "sepal_length,sepal_width,petal_length,petal_width,species"
  s3_path: "clean_data"
split:
  clean_data: "../clean_data/data/iris.csv"
  test_size: 0.3
  random_seed: 42
  file_names: "iris_train.csv,iris_test.csv"
  s3_path: "splitted_data"
train:
  train_data: "../split_data/data/iris_train.csv"
  target: "species"
  model_config: "model_config.json"
  model_name: "model.joblib"
  s3_path: "model"
test:
  test_data: "../split_data/data/iris_test.csv"
  target: "species"
  model_path: "../train_model/model/model.joblib"
